version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Porta para o gateway de serviços
      - "8000:8000" # Porta para o DynamoDB
    environment:
      - SERVICES=dynamodb,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack" # Persistência opcional
